package exception

fun main(){
    // O bloco try/cach pode servir como uma expressÃ£o
    print("> ")
    val v = try {
        readln().toInt()
    }
    catch (ex: NumberFormatException){
        0
    }

    println("I = $v")
}